name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib

      - name: Install lcov
        run: sudo apt install lcov

      - name: Build
        run: mkdir build && cd build && cmake .. && make

      - name: Static Analis and Linters
        run: ./linters/run.sh

      - name: Tests
        run: mkdir runtests && cd runtests && cmake .. && make && ./runTests && lcov -t "hw1" -o coverage.txt -c -d . && cp coverage.txt ../

      - name: Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind && mkdir valgrind_tests && cd valgrind_tests && cmake .. && make && valgrind --tool=memcheck --leak-check=full ./runTests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests 
      


