name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y 

      - name: Install lcov
        run: sudo apt install lcov

      - name: Build
        run: mkdir build && cd build && cmake .. && make && cd ..

      - name: cppcheck install
        run: sudo apt update && sudo apt install cppcheck

      - name: cppcheck check
        run: cppcheck src tests  --enable=all --error-exitcode=1 -I include/ --suppress=missingIncludeSystem
        
      - name: cpplint install
        run: sudo apt-get install python
        
      - name: cpplint check
        run: python2.7 ./linters/cpplint/cpplint.py --extensions=c src/* include/*
        
      - name: clang-tidy install
        run: sudo apt install clang-tidy
        
      - name: clang-tidy check
        run: clang-tidy src/* -- -Iinclude/ -DMY_DEFINES ...
        
      - name: clang-format install
        run: sudo apt-get install clang-format
        
      - name: clang-format check
        run: clang-format -i src/*.c && clang-format -i include/*.h && clang-format -i tests/*.cpp
        
      - name: install scan-build
        run: sudo apt install clang-tools
        
      - name: data generate
        run: cd data && python3 data.py && cd ..
        
      - name: run tests with address sanitizer
        run: mkdir add_build && cd add_build && cmake -Daddress=ON .. && make && make test
        
      - name: run tests with memory sanitizer
        run: mkdir mem_build && cd mem_build && cmake -Dmemory=ON .. && make && make test
        
      - name: run tests with undefined sanitizer
        run: mkdir und_build && cd und_build && cmake -Dundefined=ON .. && make && make test
           
      - name: run tests with thread sanitizer
        run: mkdir thr_build && cd thr_build && cmake -Dthread=ON .. && make && make test
      
      - name: run tests with scan-build
        run: mkdir test_build && cd test_build && scan-build cmake .. && scan-build make && scan-build make test && lcov -t "hw-c" -o hw-c.info -c -d . && lcov --remove hw-c.info "/usr/include/*" "./include/*" "/usr/local/*" > coverage.info && genhtml -o report coverage.info
        
      - name: install fbinfer
        run: VERSION=1.1.0; curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" | sudo tar -C /opt -xJ && sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer
        
      - name: run with fbinfer
        run: mkdir infer_build && cd infer_build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .. && cd .. && infer run --compilation-database infer_build/compile_commands.json
        
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
       
      - name: Valgrind check
        run: mkdir valgrind_check && cd valgrind_check && cmake .. && make && valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s -q make test
      - name: coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: test_build/report
