name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: mkdir build && cd build && cmake .. && make

      - name: cppcheck-action
        run: sudo apt update && sudo apt install cppcheck

      - name: cppcheck check
        run: cppcheck ./src
      
