name: c-linter 
 
on: [pull_request] 
jobs: 
  c-linter: 
    name: c-linter 
    runs-on: ubuntu-latest 
    steps: 
      - name: c-linter 
        uses: ArtificialAmateur/cpp-linter-action@0.01
    env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
